name: sigsars
services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/initdb.sql:/docker-entrypoint-initdb.d/1.sql
      - ./docker/database/data/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/database/data/logs:/var/log/postgresql
    mem_limit: "512mb"
    cpus: "0.50"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - sigsars
  pgadmin4:
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/pgadmin/data:/var/lib/pgadmin/data
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - sigsars
networks:
  sigsars:
    driver: bridge
