CREATE TYPE "tipo_transferencia_externa" AS ENUM (
  'PORTA',
  'INTERNACAO'
);

CREATE TABLE "unidades" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "numero_leitos_uti" INT,
  "numero_leitos_enfermaria" INT,
  "numero_leitos_suporte_ventilatorio_pulmonar" INT,
  "tipo_unidade_id" INT,
  "criado_em" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "atualizado_em" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "tipos_unidades" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT UNIQUE NOT NULL
);

CREATE TABLE "boletins" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unidade_id" INT NOT NULL,
  "responsavel" TEXT NOT NULL,
  "referente_ao_dia" DATE NOT NULL,
  "admissoes_srag" INT NOT NULL,
  "admissoes_nao_srag" INT NOT NULL,
  "atendimentos_gripal_sd" INT NOT NULL,
  "atendimentos_nao_gripal_sd" INT NOT NULL,
  "atendimentos_gripal_sn" INT NOT NULL,
  "atendimentos_nao_gripal_sn" INT NOT NULL,
  "pacientes_uti" INT NOT NULL,
  "pacientes_enfermaria" INT NOT NULL,
  "pacientes_lsvp" INT NOT NULL,
  "pacientes_estabilizacao_vermelha" INT NOT NULL,
  "transferencias_externas_id" INT NOT NULL,
  "altas" INT NOT NULL,
  "evasao" INT NOT NULL,
  "obitos" INT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "atualizado_em" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "transferencias_externas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "boletim_id" INT NOT NULL,
  "unidade_destino_id" INT NOT NULL,
  "tipo" tipo_transferencia_externa NOT NULL,
  "quantidade" INT NOT NULL
);

ALTER TABLE "unidades" ADD FOREIGN KEY ("tipo_unidade_id") REFERENCES "tipos_unidades" ("id");

ALTER TABLE "boletins" ADD FOREIGN KEY ("unidade_id") REFERENCES "unidades" ("id");

ALTER TABLE "boletins" ADD FOREIGN KEY ("transferencias_externas_id") REFERENCES "transferencias_externas" ("id");

ALTER TABLE "transferencias_externas" ADD FOREIGN KEY ("boletim_id") REFERENCES "boletins" ("id");
