CREATE TYPE "tipo_origem_atendimento_porta" AS ENUM (
  'DEMANDA_ESPONTANEA_SAO_LUIS',
  'DEMANDA_ESPONTANEA_INTERIOR',
  'REFERENCIADO_UPAS',
  'REFERENCIADO_APS',
  'REFERENCIADO_CLINICAS',
  'OUTROS'
);

CREATE TYPE "tipo_local_de_saida" AS ENUM (
  'PORTA',
  'INTERNACAO'
);

CREATE TYPE "tipo_leito_de_destino" AS ENUM (
  'ENFERMARIA_CLINICA',
  'ENFERMARIA_CIRURGICA',
  'HEMODINAMICA',
  'VERMELHA',
  'UTI'
);

CREATE TYPE "tipo_saida" AS ENUM (
  'ALTA',
  'EVASAO',
  'OBITO',
  'TRANSFERENCIA'
);

CREATE TYPE "tipo_genero" AS ENUM (
  'M',
  'F'
);

CREATE TYPE "tipo_admissao" AS ENUM (
  'PORTA',
  'INTERNACAO'
);

CREATE TYPE "tipo_turno" AS ENUM (
  'SERVICO_DIURNO',
  'SERVICO_NOTURNO'
);

CREATE TYPE "tipo_boletim" AS ENUM (
  'ADMISSAO_INTERNACAO',
  'ATENDIMENTO',
  'SAIDA',
  'INTERNACAO'
);

CREATE TYPE "tipo_causa" AS ENUM (
  'QUEIXA',
  'EXTERNA'
);

CREATE TABLE "unidade" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "sigla" TEXT,
  "endereco" TEXT,
  "cnes" TEXT,
  "cnpj" TEXT,
  "email_principal" TEXT,
  "email_alternativo" TEXT,
  "numero_leitos_uti" INT,
  "numero_leitos_uci" INT,
  "numero_leitos_enfermaria" INT,
  "numero_leitos_suporte_ventilatorio_pulmonar" INT,
  "numero_leitos_existente_total" INT,
  "numero_leitos_cnes_total" INT,
  "unidade_tipo_id" INT,
  "setor" TEXT,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "unidade_tipo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT UNIQUE NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "boletim_atendimento_porta" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unidade_id" INT NOT NULL,
  "usuario_responsavel_preenchimento_id" UUID NOT NULL,
  "referente_ao_dia" DATE NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "boletim_atendimento_porta_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "boletim_atendimento_porta_id" INT,
  "origem" tipo_origem_atendimento_porta,
  "turno" tipo_turno,
  "numero_de_atendimentos" INT NOT NULL,
  "causa_id" INT,
  "genero" tipo_genero,
  "faixa_etaria" TEXT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "boletim_internacao_admissao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unidade_id" INT NOT NULL,
  "usuario_responsavel_preenchimento_id" UUID NOT NULL,
  "referente_ao_dia" DATE NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "boletim_admissoao_internacao_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "boletim_internacao_admissao_id" INT,
  "numero_de_admissoes" INT NOT NULL,
  "cid_id" INT,
  "faixa_etaria" TEXT NOT NULL,
  "genero" tipo_genero,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "boletim_internacao_ocupacao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unidade_id" INT NOT NULL,
  "usuario_responsavel_preenchimento_id" UUID NOT NULL,
  "referente_ao_dia" DATE NOT NULL,
  "pacientes_uti" INT NOT NULL,
  "pacientes_uti_isolamento" INT NOT NULL,
  "pacientes_enfermaria" INT NOT NULL,
  "pacientes_enfermaria_isolamento" INT NOT NULL,
  "pacientes_lsvp" INT NOT NULL,
  "pacientes_estabilizacao_vermelha" INT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "boletim_saida" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unidade_id" INT NOT NULL,
  "usuario_responsavel_preenchimento_id" UUID NOT NULL,
  "local_de_saida" tipo_local_de_saida NOT NULL,
  "tipo_da_saida" tipo_saida NOT NULL,
  "unidade_destino_id" INT NOT NULL,
  "leito_de_destino" tipo_leito_de_destino,
  "total_de_saida" INT NOT NULL
);

CREATE TABLE "cid_grupo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_categoria_inicio" TEXT NOT NULL,
  "codigo_categoria_fim" TEXT NOT NULL,
  "descricao" TEXT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "cid_categoria" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cid_grupo_id" INT NOT NULL,
  "codigo" TEXT NOT NULL,
  "descricao" TEXT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "cid" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cid_categoria_id" INT NOT NULL,
  "codigo" TEXT NOT NULL,
  "patologia" TEXT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);


CREATE TABLE "cid_srag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cid_id" INT,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "causa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT,
  "tipo" tipo_causa,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "causa_srag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "causa_id" INT,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "usuario_tipo"(
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT,
  "descricao" TEXT,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "usuario"(
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "nome" TEXT NOT NULL,
  "cargo" TEXT NOT NULL,
  "matricula" TEXT NOT NULL UNIQUE,
  "cpf" TEXT NOT NULL UNIQUE,
  "email" TEXT,
  "usuario_tipo_id" INT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "acesso" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" UUID NOT NULL UNIQUE,
  "senha" TEXT NOT NULL,
  "ultimo_login" TIMESTAMP,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "token_de_acesso" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "acesso_id" INT NOT NULL,
    "token" TEXT UNIQUE NOT NULL,
    "valido_ate"  TIMESTAMP NOT NULL,
    "expirado_em" TIMESTAMP,
    "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
    "atualizado_em" TIMESTAMP
);

ALTER TABLE "boletim_internacao_admissao" ADD FOREIGN KEY ("unidade_id") REFERENCES "unidade" ("id");

ALTER TABLE "boletim_internacao_ocupacao" ADD FOREIGN KEY ("unidade_id") REFERENCES "unidade" ("id");

ALTER TABLE "boletim_atendimento_porta" ADD FOREIGN KEY ("unidade_id") REFERENCES "unidade" ("id");

ALTER TABLE "boletim_saida" ADD FOREIGN KEY ("unidade_id") REFERENCES "unidade" ("id");

ALTER TABLE "boletim_saida" ADD FOREIGN KEY ("unidade_destino_id") REFERENCES "unidade" ("id");

ALTER TABLE "boletim_atendimento_porta_item" ADD FOREIGN KEY ("causa_id") REFERENCES "causa" ("id");

ALTER TABLE "causa_srag" ADD FOREIGN KEY ("causa_id") REFERENCES "causa" ("id");

ALTER TABLE "boletim_atendimento_porta_item" ADD FOREIGN KEY ("boletim_atendimento_porta_id") REFERENCES "boletim_atendimento_porta" ("id");

ALTER TABLE "boletim_admissoao_internacao_item" ADD FOREIGN KEY ("boletim_internacao_admissao_id") REFERENCES "boletim_internacao_admissao" ("id");

ALTER TABLE "boletim_admissoao_internacao_item" ADD FOREIGN KEY ("cid_id") REFERENCES "cid" ("id");

ALTER TABLE "cid_srag" ADD FOREIGN KEY ("cid_id") REFERENCES "cid" ("id");

ALTER TABLE "cid" ADD FOREIGN KEY ("cid_categoria_id") REFERENCES "cid_categoria" ("id");

ALTER TABLE "cid_categoria" ADD FOREIGN KEY ("cid_grupo_id") REFERENCES "cid_grupo" ("id");

ALTER TABLE "unidade" ADD FOREIGN KEY ("unidade_tipo_id") REFERENCES "unidade_tipo" ("id");

ALTER TABLE "usuario" ADD FOREIGN KEY ("usuario_tipo_id") REFERENCES "usuario_tipo" ("id");

ALTER TABLE "acesso" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") ON DELETE CASCADE;

ALTER TABLE "token_de_acesso" ADD FOREIGN KEY ("acesso_id") REFERENCES "acesso" ("id") ON DELETE CASCADE;

ALTER TABLE "boletim_saida" ADD FOREIGN KEY ("usuario_responsavel_preenchimento_id") REFERENCES "usuario"("id");

ALTER TABLE "boletim_atendimento_porta" ADD FOREIGN KEY ("usuario_responsavel_preenchimento_id") REFERENCES "usuario"("id");

ALTER TABLE "boletim_internacao_admissao" ADD FOREIGN KEY ("usuario_responsavel_preenchimento_id") REFERENCES "usuario"("id");

ALTER TABLE "boletim_internacao_ocupacao" ADD FOREIGN KEY ("usuario_responsavel_preenchimento_id") REFERENCES "usuario"("id");