CREATE TYPE "tipo_origem" AS ENUM (
  'DEMANDA_ESPONTANEA_SAO_LUIS',
  'DEMANDA_ESPONTANEA_INTERIOR',
  'REFERENCIADO_UPAS',
  'REFERENCIADO_APS',
  'REFERENCIADO_CLINICAS',
  'OUTROS'
);

CREATE TYPE "tipo_local_de_saida" AS ENUM (
  'PORTA',
  'INTERNACAO'
);

CREATE TYPE "tipo_raca_cor" AS ENUM (
  'BRANCA',
  'PRETA',
  'PARDA',
  'AMARELA',
  'INDIGENA'
);

CREATE TYPE "tipo_leito_de_destino" AS ENUM (
  'ENFERMARIA_CLINICA',
  'ENFERMARIA_CIRURGICA',
  'HEMODINAMICA',
  'VERMELHA',
  'UTI'
);

CREATE TYPE "tipo_saida" AS ENUM (
  'ALTA',
  'EVASAO',
  'OBITO',
  'TRANSFERENCIA'
);

CREATE TYPE "tipo_genero" AS ENUM (
  'M',
  'F'
);

CREATE TYPE "tipo_admissao" AS ENUM (
  'PORTA',
  'INTERNACAO'
);

CREATE TYPE "tipo_turno" AS ENUM (
  'SERVICO_DIURNO',
  'SERVICO_NOTURNO'
);

CREATE TYPE "tipo_boletim" AS ENUM (
  'ADMISSAO_INTERNACAO',
  'ATENDIMENTO',
  'SAIDA',
  'INTERNACAO'
);

CREATE TYPE "tipo_causa" AS ENUM (
  'QUEIXA',
  'EXTERNA'
);

CREATE TYPE "tipo_manchester" AS ENUM (
  'AZUL',
  'VERDE',
  'AMARELO',
  'LARANJA',
  'VERMELHO'
);

CREATE TYPE "tipo_destino_final" AS ENUM (
  'ALTA',
  'ALTA_COM_DECLARACAO_DE_COMPARECIMENTO',
  'ALTA_COM_ATESTADO_MEDICO',
  'EVASAO',
  'TRANSFERIDO',
  'INTERNADO',
  'OBITO',
  'NAO_SE_APLICA'
);

CREATE TYPE "tipo_encaminhamento" AS ENUM (
  'ESTABILIZACAO',
  'ODONTOLOGIA',
  'CLINICO',
  'ECG',
  'CURATIVO',
  'SUTURA',
  'VACIONA_ANTIRRABICA',
  'TROCA_DE_SONDA'
);

CREATE TYPE "tipo_servico" AS ENUM (
  'URGENCIA_EMERGENCIA',
  'ATENCAO_PRIMARIA',
  'AMBULATORIO',
  'HOSPITALAR',
  'LABORATORIO'
);

CREATE TABLE "regiao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "estado" (
  "id" INT PRIMARY KEY NOT NULL,
  "nome" TEXT UNIQUE NOT NULL,
  "uf" TEXT UNIQUE NOT NULL,
  "regiao_id" INT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "municipio" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_ibge" TEXT NOT NULL,
  "estado_id" INT NOT NULL,
  "nome" TEXT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "unidade" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "sigla" TEXT,
  "endereco" TEXT,
  "cnes" TEXT,
  "cnpj" TEXT,
  "email_principal" TEXT,
  "email_alternativo" TEXT,
  "numero_leitos_uti" INT,
  "numero_leitos_uci" INT,
  "numero_leitos_enfermaria" INT,
  "numero_leitos_suporte_ventilatorio_pulmonar" INT,
  "numero_leitos_existente_total" INT,
  "numero_leitos_cnes_total" INT,
  "unidade_tipo_id" INT,
  "setor" TEXT,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "unidade_tipo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT UNIQUE NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "ficha_spa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unidade_id" INT NOT NULL,
  "usuario_responsavel_preenchimento_id" UUID NOT NULL,
  "data_da_ficha" DATE NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "ficha_spa_recepcao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_spa_id" INT,
  "hora_da_recepcao" time NOT NULL,
  "nao_identificado" bool DEFAULT false,
  "nome_paciente" text,
  "genero" tipo_genero,
  "data_de_nascimento" DATE,
  "cartao_sus_ou_cpf" TEXT,
  "municipio_rg_id" INT,
  "raca_cor" tipo_raca_cor,
  "procedencia" tipo_origem,
  "municipio_procedencia_interior_id" INT,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "ficha_spa_classificacao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_spa_id" INT,
  "hora_da_classificacao" TIME NOT NULL,
  "retornou_com_menos_ou_igual_48h" BOOLEAN NOT NULL,
  "causa_externa_id" INT,
  "manchester" tipo_manchester NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "ficha_spa_encaminhamento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_spa_classificacao_id" INT,
  "encaminhado_para_1" tipo_encaminhamento NOT NULL,
  "encaminhado_para_2" tipo_encaminhamento NOT NULL,
  "hora_da_realizacao_ecg" TIME,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "ficha_spa_doenca_preexistente" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_spa_classificacao_id" INT NOT NULL,
  "has" bool NOT NULL,
  "dm" bool NOT NULL,
  "drc" bool NOT NULL,
  "outros" TEXT,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "ficha_spa_protocolo_e_condicao_especial" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_spa_classificacao_id" INT NOT NULL,
  "sepse" BOOLEAN NOT NULL,
  "dor_toracica" BOOLEAN NOT NULL,
  "avc" BOOLEAN NOT NULL,
  "notificacao" BOOLEAN NOT NULL,
  "notificacao_agravo_id" INT,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "ficha_spa_queixa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_spa_classificacao_id" INT,
  "causa_id" INT,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "ficha_spa_atendimento_medico" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "horario_do_atendimento_medico" TIME NOT NULL,
  "ficha_spa_id" INT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "ficha_spa_plano_terapeutico" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_spa_id" INT NOT NULL,
  "horario_do_atentimento_na_medicacao_observacao" TIME,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "ficha_spa_destino_final_do_paciente" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_spa_id" INT NOT NULL,
  "horario_da_saida" TIME,
  "destino_final" tipo_destino_final,
  "unidade_transferida_id" INT,
  "horario_da_saida_para_o_setor_de_internacao" TIME,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "ficha_spa_exame_solicitado" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ficha_spa_atendimento_medico_id" INT NOT NULL,
  "raio_x" BOOLEAN,
  "tomografia" BOOLEAN,
  "ecg" BOOLEAN,
  "ultrassonografia" BOOLEAN,
  "laboratorio" BOOLEAN,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "boletim_sindrome_gripal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unidade_id" INT NOT NULL,
  "usuario_responsavel_preenchimento_id" UUID,
  "referente_ao_dia" DATE NOT NULL,
  "numero_atendimentos_sd_com_queixa_gripal" INT NOT NULL,
  "numero_atendimentos_sd_sem_queixa_gripal" INT NOT NULL,
  "numero_atendimentos_sn_com_queixa_gripal" INT NOT NULL,
  "numero_atendimentos_sn_sem_queixa_gripal" INT NOT NULL,
  "numero_internacoes_apos_atendimento_na_urgencia_com_relacao_a_queixa_gripal" INT NOT NULL,
  "numero_internacoes_apos_atendimento_na_urgencia_sem_relacao_a_queixa_gripal" INT NOT NULL,
  "numero_obitos" INT NOT NULL,
  "numero_transferencias" INT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "boletim_internacao_admissao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unidade_id" INT NOT NULL,
  "usuario_responsavel_preenchimento_id" UUID NOT NULL,
  "referente_ao_dia" DATE NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "boletim_internacao_admissao_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "boletim_internacao_admissao_id" INT,
  "numero_de_admissoes" INT NOT NULL,
  "cid_id" INT,
  "faixa_etaria" TEXT NOT NULL,
  "genero" tipo_genero,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "boletim_internacao_ocupacao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unidade_id" INT NOT NULL,
  "usuario_responsavel_preenchimento_id" UUID NOT NULL,
  "referente_ao_dia" DATE NOT NULL,
  "pacientes_uti" INT NOT NULL,
  "pacientes_uti_isolamento" INT NOT NULL,
  "pacientes_enfermaria" INT NOT NULL,
  "pacientes_enfermaria_isolamento" INT NOT NULL,
  "pacientes_lsvp" INT NOT NULL,
  "pacientes_estabilizacao_vermelha" INT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "boletim_saida" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unidade_id" INT NOT NULL,
  "usuario_responsavel_preenchimento_id" UUID NOT NULL,
  "referente_ao_dia" DATE NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "boletim_saida_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "boletim_saida_id" INT,
  "local_de_saida" tipo_local_de_saida NOT NULL,
  "tipo_da_saida" tipo_saida NOT NULL,
  "unidade_destino_id" INT NOT NULL,
  "leito_de_destino" tipo_leito_de_destino,
  "total_de_saida" INT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "cid_grupo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_categoria_inicio" TEXT NOT NULL,
  "codigo_categoria_fim" TEXT NOT NULL,
  "descricao" TEXT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "cid_categoria" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cid_grupo_id" INT NOT NULL,
  "codigo" TEXT NOT NULL,
  "descricao" TEXT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "cid" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cid_categoria_id" INT NOT NULL,
  "codigo" TEXT NOT NULL,
  "patologia" TEXT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "cid_srag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cid_id" INT,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "causa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT,
  "tipo" tipo_causa,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "causa_sg" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "causa_id" INT,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "usuario_tipo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT,
  "descricao" TEXT,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "usuario" (
  "id" UUID PRIMARY KEY DEFAULT (gen_random_uuid()),
  "nome" TEXT NOT NULL,
  "cargo" TEXT NOT NULL,
  "matricula" TEXT UNIQUE NOT NULL,
  "cpf" TEXT UNIQUE NOT NULL,
  "email" TEXT,
  "usuario_tipo_id" INT NOT NULL,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "acesso" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" UUID UNIQUE NOT NULL,
  "senha" TEXT NOT NULL,
  "ultimo_login" TIMESTAMP,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "token_de_acesso" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "acesso_id" INT NOT NULL,
  "token" TEXT UNIQUE NOT NULL,
  "valido_ate" TIMESTAMP NOT NULL,
  "expirado_em" TIMESTAMP,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

CREATE TABLE "notificacao_agravo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_agravo" TEXT,
  "tipo_notificacao" TEXT,
  "sistema_notificacao" TEXT,
  "servicos_permitidos" tipo_servico[],
  "observacoes" TEXT,
  "ativo" BOOLEAN DEFAULT true,
  "criado_em" TIMESTAMP DEFAULT (CURRENT_TIMESTAMP),
  "atualizado_em" TIMESTAMP
);

ALTER TABLE "estado" ADD FOREIGN KEY ("regiao_id") REFERENCES "regiao" ("id");

ALTER TABLE "municipio" ADD FOREIGN KEY ("estado_id") REFERENCES "estado" ("id");

ALTER TABLE "ficha_spa_recepcao" ADD FOREIGN KEY ("municipio_rg_id") REFERENCES "municipio" ("id");

ALTER TABLE "ficha_spa_recepcao" ADD FOREIGN KEY ("municipio_procedencia_interior_id") REFERENCES "municipio" ("id");

ALTER TABLE "ficha_spa_classificacao" ADD FOREIGN KEY ("ficha_spa_id") REFERENCES "ficha_spa" ("id");

ALTER TABLE "ficha_spa_classificacao" ADD FOREIGN KEY ("causa_externa_id") REFERENCES "causa" ("id");

ALTER TABLE "ficha_spa_encaminhamento" ADD FOREIGN KEY ("ficha_spa_classificacao_id") REFERENCES "ficha_spa_classificacao" ("id");

ALTER TABLE "ficha_spa_doenca_preexistente" ADD FOREIGN KEY ("ficha_spa_classificacao_id") REFERENCES "ficha_spa_classificacao" ("id");

ALTER TABLE "ficha_spa_protocolo_e_condicao_especial" ADD FOREIGN KEY ("ficha_spa_classificacao_id") REFERENCES "ficha_spa_classificacao" ("id");

ALTER TABLE "ficha_spa_protocolo_e_condicao_especial" ADD FOREIGN KEY ("notificacao_agravo_id") REFERENCES "notificacao_agravo" ("id");

ALTER TABLE "ficha_spa_queixa" ADD FOREIGN KEY ("ficha_spa_classificacao_id") REFERENCES "ficha_spa_classificacao" ("id");

ALTER TABLE "ficha_spa_queixa" ADD FOREIGN KEY ("causa_id") REFERENCES "causa" ("id");

ALTER TABLE "ficha_spa_atendimento_medico" ADD FOREIGN KEY ("ficha_spa_id") REFERENCES "ficha_spa" ("id");

ALTER TABLE "ficha_spa_plano_terapeutico" ADD FOREIGN KEY ("ficha_spa_id") REFERENCES "ficha_spa" ("id");

ALTER TABLE "ficha_spa_destino_final_do_paciente" ADD FOREIGN KEY ("ficha_spa_id") REFERENCES "ficha_spa" ("id");

ALTER TABLE "ficha_spa_destino_final_do_paciente" ADD FOREIGN KEY ("unidade_transferida_id") REFERENCES "unidade" ("id");

ALTER TABLE "ficha_spa_exame_solicitado" ADD FOREIGN KEY ("ficha_spa_atendimento_medico_id") REFERENCES "ficha_spa_atendimento_medico" ("id");

ALTER TABLE "boletim_sindrome_gripal" ADD FOREIGN KEY ("unidade_id") REFERENCES "unidade" ("id");

ALTER TABLE "boletim_sindrome_gripal" ADD FOREIGN KEY ("usuario_responsavel_preenchimento_id") REFERENCES "usuario" ("id");

ALTER TABLE "boletim_internacao_admissao" ADD FOREIGN KEY ("unidade_id") REFERENCES "unidade" ("id");

ALTER TABLE "boletim_internacao_ocupacao" ADD FOREIGN KEY ("unidade_id") REFERENCES "unidade" ("id");

ALTER TABLE "ficha_spa" ADD FOREIGN KEY ("unidade_id") REFERENCES "unidade" ("id");

ALTER TABLE "boletim_saida" ADD FOREIGN KEY ("unidade_id") REFERENCES "unidade" ("id");

ALTER TABLE "causa_sg" ADD FOREIGN KEY ("causa_id") REFERENCES "causa" ("id");

ALTER TABLE "ficha_spa_recepcao" ADD FOREIGN KEY ("ficha_spa_id") REFERENCES "ficha_spa" ("id") ON DELETE CASCADE;

ALTER TABLE "boletim_internacao_admissao_item" ADD FOREIGN KEY ("boletim_internacao_admissao_id") REFERENCES "boletim_internacao_admissao" ("id") ON DELETE CASCADE;

ALTER TABLE "boletim_internacao_admissao_item" ADD FOREIGN KEY ("cid_id") REFERENCES "cid" ("id");

ALTER TABLE "cid_srag" ADD FOREIGN KEY ("cid_id") REFERENCES "cid" ("id");

ALTER TABLE "cid" ADD FOREIGN KEY ("cid_categoria_id") REFERENCES "cid_categoria" ("id");

ALTER TABLE "cid_categoria" ADD FOREIGN KEY ("cid_grupo_id") REFERENCES "cid_grupo" ("id");

ALTER TABLE "unidade" ADD FOREIGN KEY ("unidade_tipo_id") REFERENCES "unidade_tipo" ("id");

ALTER TABLE "usuario" ADD FOREIGN KEY ("usuario_tipo_id") REFERENCES "usuario_tipo" ("id");

ALTER TABLE "acesso" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") ON DELETE CASCADE;

ALTER TABLE "token_de_acesso" ADD FOREIGN KEY ("acesso_id") REFERENCES "acesso" ("id") ON DELETE CASCADE;

ALTER TABLE "boletim_saida" ADD FOREIGN KEY ("usuario_responsavel_preenchimento_id") REFERENCES "usuario" ("id");

ALTER TABLE "ficha_spa" ADD FOREIGN KEY ("usuario_responsavel_preenchimento_id") REFERENCES "usuario" ("id");

ALTER TABLE "boletim_internacao_admissao" ADD FOREIGN KEY ("usuario_responsavel_preenchimento_id") REFERENCES "usuario" ("id");

ALTER TABLE "boletim_internacao_ocupacao" ADD FOREIGN KEY ("usuario_responsavel_preenchimento_id") REFERENCES "usuario" ("id");

ALTER TABLE "boletim_saida_item" ADD FOREIGN KEY ("boletim_saida_id") REFERENCES "boletim_saida" ("id") ON DELETE CASCADE;
